### ISSUE TITLE
I am using list task method , but it is not working . I am facing an error

### ISSUE THREAD

**Issue by skarifhossain** [tomwalder/php-appengine-pull-queue#6]
I  am using list task method , but it is not working . I am facing an error .

We put Queue.php and Task.php under AEQ folder
Declear namespace AEQ; for both  file  Queue.php and Task.php
Add task and lease & delete task working well..

But list task not working . Please check below code

include_once 'AEQ/Task.php';
include_once 'AEQ/Queue.php';

$obj_task = new AEQ\Task();
$obj_queue = new AEQ\Queue('queue_name');

// List Tasks
foreach($obj_queue->listTasks() as $obj_task) {
   echo $obj_task->getName();
}

Using this code I got an error i.e 

Fatal error: Uncaught exception 'RuntimeException' with message 'Failed to execute call [QueryTasks] with: 9 (PERMISSION_DENIED)' in /base/data/home/apps/s~project/1.390926642656759954/public/pull/AEQ/Queue.php:223 Stack trace: #0 /base/data/home/apps/s~project/1.390926642656759954/public/pull/AEQ/Queue.php(197): AEQ\Queue->makeCall('QueryTasks', Object(google\appengine\TaskQueueQueryTasksRequest), Object(google\appengine\TaskQueueQueryTasksResponse)) #1 /base/data/home/apps/s~project/1.390926642656759954/public/pull/listtask.php(12): AEQ\Queue->listTasks() #2 {main} thrown in /base/data/home/apps/s~project/1.390926642656759954/public/pull/AEQ/Queue.php on line 223 

Please give me solution

**Comment by tomwalder** [comment]
Is the queue a pull queue?

**Comment by skarifhossain** [comment]
yes..tom ...

**Comment by tomwalder** [comment]
I see the same error on AppEngine. Works locally.  I may have to raise a query with the Google team.
